services:
  api:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - ../files/data:/app/data
      - ../files/credentials.json:/app/data/credentials.json
      - ../files/tg.session:/app/data/tg.session
    environment:
      - Telegram__ApiId=${TELEGRAM_API_ID}
      - Telegram__ApiHash=${TELEGRAM_API_HASH}
      - Telegram__Channel=${TELEGRAM_CHANNEL}
      - Telegram__PhoneNumber=${TELEGRAM_PHONE}
      - Google__SpreadsheetId=${GOOGLE_SPREADSHEET_ID}
      - Google__Range=${GOOGLE_RANGE}
      - Google__CredentialsFilePath=/app/data/credentials.json