services:
  api:
    image: vafelka/missile-predictor:latest
    environment:
      ASPNETCORE_URLS: http://+:8080
      Telegram__ApiId: ${TELEGRAM_API_ID}
      Telegram__ApiHash: ${TELEGRAM_API_HASH}
      Telegram__Channel: ${TELEGRAM_CHANNEL}
      Telegram__PhoneNumber: ${TELEGRAM_PHONE_NUMBER}
      Telegram__SessionPath: /app/WTelegram.session
      Telegram__LastIdPath: /app/msg.json
      ML__ModelPath: /app/models/sentiment.zip
    ports:
      - "3000:8080"
    volumes:
      - ./tg.session:/app/WTelegram.session:rw
      - ./models/sentiment.zip:/app/models/sentiment.zip:ro
    restart: unless-stopped
